sudo: required

language: minimal

services:
  - docker

before_install:
  - docker pull bottalk/cli
  
script:
  - for D in */; do docker run --rm -v "./${D}:/root/app" bottalk/cli --dir /root/app test; done
